"""Descreva sua alteração

Revision ID: 04335547afbb
Revises: 5603c97b2bfe
Create Date: 2025-05-23 13:06:53.045618

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '04335547afbb'
down_revision: Union[str, None] = '5603c97b2bfe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('nomes_pasta', sa.Column('sobrenome_original', sa.String(), nullable=True))
    op.add_column('nomes_pasta', sa.Column('sobrenome_sugerido', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('nomes_pasta', 'sobrenome_sugerido')
    op.drop_column('nomes_pasta', 'sobrenome_original')
    # ### end Alembic commands ###
