"""Permite NULL em nome_original

Revision ID: 07f2af9a68a1
Revises: 9f8a831de5b4
Create Date: 2025-05-23 13:41:58.877469

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '07f2af9a68a1'
down_revision: Union[str, None] = '9f8a831de5b4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('nomes_pasta', 'nome_original',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('nomes_pasta', 'nome_original',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
