"""Adiciona colunas nomes_padrao e sobrenomes_padrao

Revision ID: 7c462eda4f7c
Revises: dbd10d6ce528
Create Date: 2025-05-23 13:21:14.317430

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7c462eda4f7c'
down_revision: Union[str, None] = 'dbd10d6ce528'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('nomes_comuns', sa.Column('nomes_padrao', sa.Boolean(), nullable=True))
    op.add_column('nomes_comuns', sa.Column('sobrenomes_padrao', sa.Boolean(), nullable=True))
    op.drop_column('nomes_comuns', 'nomes')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('nomes_comuns', sa.Column('nomes', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('nomes_comuns', 'sobrenomes_padrao')
    op.drop_column('nomes_comuns', 'nomes_padrao')
    # ### end Alembic commands ###
