"""Adiciona colunas nome_padrao e sobrenome_padrao

Revision ID: 9f8a831de5b4
Revises: 7c462eda4f7c
Create Date: 2025-05-23 13:26:56.857375

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9f8a831de5b4'
down_revision: Union[str, None] = '7c462eda4f7c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('nomes_comuns')
    op.add_column('nomes_pasta', sa.Column('nome_padrao', sa.Boolean(), nullable=True))
    op.add_column('nomes_pasta', sa.Column('sobrenome_padrao', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('nomes_pasta', 'sobrenome_padrao')
    op.drop_column('nomes_pasta', 'nome_padrao')
    op.create_table('nomes_comuns',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('nomes_padrao', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('sobrenomes_padrao', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('nomes_comuns_pkey')),
    sa.UniqueConstraint('nome', name=op.f('nomes_comuns_nome_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    # ### end Alembic commands ###
